import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { sendNotification } from "npm:@mmmike/web-push";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const VAPID_PUBLIC_KEY=Deno.env.get("VAPID_PUBLIC_KEY")!;
const VAPID_PRIVATE_KEY=Deno.env.get("VAPID_PRIVATE_KEY")!;
const VAPID_SUBJECT=Deno.env.get("VAPID_SUBJECT")||"mailto:fxsignal@example.com";
const supabase=createClient(SUPABASE_URL,SUPABASE_SERVICE_ROLE_KEY);
type E={id:string,date:string,time:string,country:string|null,title:string,type:string|null,importance:number|null};
type S={id:string,endpoint:string,p256dh:string,auth:string,enabled:boolean,notify_importance_1:boolean,notify_importance_2:boolean,notify_importance_3:boolean,notify_rates:boolean,notify_central_bank:boolean,notify_speech:boolean,notify_60:boolean,notify_30:boolean,notify_5:boolean,notify_0:boolean};
const eventMs=(e:E)=>Date.parse(`${e.date}T${String(e.time||"00:00:00").slice(0,8)}Z`);
function allowed(s:S,e:E){if(!s.enabled)return false;if(e.type==="rate")return s.notify_rates;if(e.type==="central_bank")return s.notify_central_bank;if(e.type==="speech")return s.notify_speech;const i=Math.max(1,Math.min(3,Number(e.importance||1)));return i>=3?s.notify_importance_3:i===2?s.notify_importance_2:s.notify_importance_1}
function timings(s:S){const a:number[]=[];if(s.notify_60)a.push(60);if(s.notify_30)a.push(30);if(s.notify_5)a.push(5);if(s.notify_0)a.push(0);return a}
function stars(e:E){const i=Math.max(1,Math.min(3,Number(e.importance||1)));return "★".repeat(i)+"☆".repeat(3-i)}
function kind(e:E){if(e.type==="rate")return"政策金利";if(e.type==="central_bank")return"中央銀行関連";if(e.type==="speech")return"要人発言";const i=Math.max(1,Math.min(3,Number(e.importance||1)));return i>=3?"重要指標":i===2?"注目指標":"参考指標"}
async function sent(eventId:string,subId:string,t:number){const {data,error}=await supabase.from("push_notification_log").select("id").eq("event_id",eventId).eq("subscription_id",subId).eq("timing_minutes",t).maybeSingle();if(error)throw error;return!!data}
async function mark(eventId:string,subId:string,t:number){const {error}=await supabase.from("push_notification_log").insert({event_id:eventId,subscription_id:subId,timing_minutes:t});if(error&&error.code!=="23505")throw error}
Deno.serve(async()=>{try{const now=Date.now();const from=new Date(now-90000).toISOString().slice(0,10);const to=new Date(now+61*60000).toISOString().slice(0,10);const {data:events,error:ee}=await supabase.from("events").select("id,date,time,country,title,type,importance").gte("date",from).lte("date",to);if(ee)throw ee;const {data:subs,error:se}=await supabase.from("push_subscriptions").select("*").eq("enabled",true);if(se)throw se;let count=0,disabled=0;for(const e of (events||[]) as E[]){const em=eventMs(e);if(!Number.isFinite(em))continue;for(const s of (subs||[]) as S[]){if(!allowed(s,e))continue;for(const t of timings(s)){const late=now-(em-t*60000);if(late<0||late>75000)continue;if(await sent(e.id,s.id,t))continue;const payload=JSON.stringify({title:"FX SIGNAL",body:`${t===0?"まもなく発表":t+"分前"}｜${kind(e)} ${stars(e)}｜${e.title}`,tag:`fxsignal-${e.id}-${t}`,eventKey:e.id,url:"./"});try{await sendNotification({endpoint:s.endpoint,keys:{p256dh:s.p256dh,auth:s.auth}},payload,{vapidDetails:{subject:VAPID_SUBJECT,publicKey:VAPID_PUBLIC_KEY,privateKey:VAPID_PRIVATE_KEY},ttl:300,urgency:t<=5?"high":"normal"});await mark(e.id,s.id,t);count++}catch(err){const code=typeof err==="object"&&err&&"statusCode" in err?Number((err as {statusCode?:number}).statusCode):0;if(code===404||code===410){await supabase.from("push_subscriptions").update({enabled:false}).eq("id",s.id);disabled++}else console.error("push failed",s.id,e.id,t,err)}}}}return Response.json({ok:true,sent:count,disabled,events:events?.length||0,subscriptions:subs?.length||0,now:new Date(now).toISOString()})}catch(error){console.error(error);return Response.json({ok:false,error:String(error)},{status:500})}});
